#include "ulog/ulog.h"
#include <stdio.h>

void text(void) 
{
    #if BENCHMARK_PRINTF_SIZE
        printf("  Lorem ipsum dolor sit amet, co");
        printf("nsectetur adipiscing elit. In si");
        printf("t amet sem eget ligula consequat");
        printf(" hendrerit. Etiam pulvinar tempo");
        printf("r lorem, lacinia dictum massa ma");
        printf("ttis ut. Mauris vulputate vulput");
        printf("ate lectus sit amet congue. Maur");
        printf("is feugiat ipsum in purus maximu");
        printf("s, quis sagittis est fermentum. ");
        printf("Nunc a lorem luctus, dapibus nis");
        printf("l sit amet, sodales lacus. Pelle");
        printf("ntesque fringilla lectus sed dia");
        printf("m convallis, sit amet dapibus lo");
        printf("rem rhoncus. Quisque laoreet lib");
        printf("ero vel efficitur varius.  In gr");
        printf("avida consectetur massa nec faci");
        printf("lisis. Integer dolor lorem, cond");
        printf("imentum ac arcu ultricies, dictu");
        printf("m faucibus dui. Sed tellus justo");
        printf(", gravida ac mattis at, semper u");
        printf("t ex. Quisque aliquam ipsum vita");
        printf("e elementum accumsan. Donec at a");
        printf("uctor dui. Sed maximus vulputate");
        printf(" lectus, vitae dignissim magna c");
        printf("ursus nec. Aenean luctus, neque ");
        printf("et scelerisque placerat, odio ni");
        printf("si sagittis augue, quis tristiqu");
        printf("e felis lacus eget arcu.  Quisqu");
        printf("e faucibus nibh risus, nec conse");
        printf("ctetur lacus condimentum nec. Se");
        printf("d vitae orci lacus. Nullam trist");
        printf("ique tempor magna, a porta orci ");
        printf("venenatis vel. Vestibulum ultric");
        printf("es sem vel nisl pharetra vulputa");
        printf("te. Ut interdum dui sed tortor m");
        printf("olestie molestie. Morbi pellente");
        printf("sque ex vel tortor placerat aliq");
        printf("uam. Vivamus velit eros, mollis ");
        printf("posuere mauris in, volutpat aliq");
        printf("uet augue. Nunc at pellentesque ");
        printf("odio. Morbi tristique turpis a e");
        printf("st tincidunt, sit amet tincidunt");
        printf(" nisl consequat. Duis vel erat l");
        printf("uctus, aliquet nulla eu, tincidu");
        printf("nt odio. Mauris hendrerit massa ");
        printf("at massa congue tristique. Pelle");
        printf("ntesque bibendum hendrerit moles");
        printf("tie. Nulla libero justo, vulputa");
        printf("te sed odio eget, mollis tempus ");
        printf("nisi. Mauris finibus vel neque q");
        printf("uis ultrices. Quisque rutrum nib");
        printf("h et turpis rutrum, et imperdiet");
        printf(" turpis pellentesque.  Nam ante ");
        printf("turpis, pharetra quis velit vel,");
        printf(" feugiat lacinia nunc. Phasellus");
        printf(" commodo sagittis nunc, ut conva");
        printf("llis mauris pretium vel. Aenean ");
        printf("felis justo, elementum id velit ");
        printf("quis, lobortis pretium dolor. Se");
        printf("d consectetur tempus ipsum at ul");
        printf("lamcorper. In a felis metus. Eti");
        printf("am scelerisque feugiat lacus vit");
        printf("ae molestie. Pellentesque vitae ");
        printf("arcu eu erat aliquet hendrerit a");
        printf("c vitae dui. In sed maximus nunc");
        printf(", lacinia dignissim risus. Nulla");
        printf(" eget urna mollis, euismod massa");
        printf(" quis, viverra mauris.  Quisque ");
        printf("dignissim consequat nunc nec fac");
        printf("ilisis. Sed molestie sem quis se");
        printf("m scelerisque, a fermentum torto");
        printf("r lacinia. Etiam tincidunt euism");
        printf("od nisl vitae auctor. Sed nec ar");
        printf("cu congue tellus facilisis lobor");
        printf("tis sit amet quis arcu. Nunc sit");
        printf(" amet orci vulputate, suscipit f");
        printf("elis non, euismod lacus. Vivamus");
        printf(" malesuada, sapien in mollis dic");
        printf("tum, mauris neque consequat risu");
        printf("s, eget sagittis ante quam ut du");
        printf("i. Suspendisse convallis tristiq");
        printf("ue nulla. Maecenas viverra metus");
        printf(" vel fringilla imperdiet. Duis i");
        printf("n magna at sapien viverra tempus");
        printf(" eu eu sapien. Integer id dignis");
        printf("sim nisl. Mauris turpis dolor, d");
        printf("ignissim in mattis malesuada, eg");
        printf("estas quis ligula. Praesent at e");
        printf("lit ultrices, consequat lorem at");
        printf(", fermentum justo. Morbi aliquam");
        printf(" ultricies molestie. Nunc finibu");
        printf("s augue sit amet est ullamcorper");
        printf(", ultricies rhoncus sapien ullam");
        printf("corper. Vestibulum ante ipsum pr");
        printf("imis in faucibus orci luctus et ");
        printf("ultrices posuere cubilia curae; ");
        printf(" Curabitur commodo turpis in pla");
        printf("cerat cursus. Fusce quis ligula ");
        printf("dignissim eros lobortis iaculis ");
        printf("eu nec dolor. Aenean eleifend fe");
        printf("lis massa, quis vehicula odio so");
        printf("llicitudin ut. Quisque quis blan");
        printf("dit lacus. Sed sit amet massa fe");
        printf("ugiat, blandit dui ac, tempor od");
        printf("io. Duis vel turpis a urna digni");
        printf("ssim faucibus. Praesent tincidun");
        printf("t turpis eu purus pretium faucib");
        printf("us. Pellentesque gravida, diam i");
        printf("d venenatis ornare, nunc nibh sa");
        printf("gittis nulla, sed porttitor ante");
        printf(" lacus in mauris. Aenean accumsa");
        printf("n elementum nisi in tristique. A");
        printf("enean turpis magna, volutpat ege");
        printf("t libero non, tincidunt porta er");
        printf("at.  Sed finibus tristique laore");
        printf("et. Nam id dolor nisi. Orci vari");
        printf("us natoque penatibus et magnis d");
        printf("is parturient montes, nascetur r");
        printf("idiculus mus. Cras ornare elemen");
        printf("tum blandit. Suspendisse tempus ");
        printf("odio nec bibendum ornare. Aliqua");
        printf("m malesuada ex at tortor ultrici");
        printf("es vulputate. Sed vehicula mauri");
        printf("s ipsum, id maximus urna sceleri");
        printf("sque ut. Maecenas facilisis veli");
        printf("t sit amet tellus iaculis, ut po");
        printf("rttitor est blandit. Suspendisse");
        printf(" ante tortor, tempor in dolor ut");
        printf(", cursus lacinia ligula. Proin h");
        printf("endrerit, nisi a semper fringill");
        printf("a, libero sapien dapibus ipsum, ");
        printf("et faucibus tortor quam eget eni");
        printf("m.  Ut tincidunt lectus vel maur");
        printf("is iaculis eleifend. Proin id ex");
        printf(" id ante dignissim auctor in nec");
        printf(" sem. Nunc consectetur cursus du");
        printf("i, vel accumsan metus dignissim ");
        printf("sit amet. Sed quis urna quis leo");
        printf(" scelerisque dapibus rutrum at l");
        printf("igula. In fermentum leo quis era");
        printf("t varius interdum. Duis vehicula");
        printf(" est imperdiet molestie bibendum");
        printf(". Morbi sagittis pretium tortor,");
        printf(" at commodo nulla tincidunt eget");
        printf(". Nunc mi ante, suscipit sit ame");
        printf("t lectus ac, vehicula volutpat l");
        printf("igula.  Cras ut nisi blandit, pu");
        printf("lvinar dui ut, egestas mauris. P");
        printf("hasellus quis augue vitae odio f");
        printf("aucibus lacinia eget sit amet du");
        printf("i. Nunc tristique, tortor non so");
        printf("dales ornare, mi leo dignissim e");
        printf("ros, ut ultrices massa ante sit ");
        printf("amet augue. Fusce molestie dui i");
        printf("d consectetur tempus. Phasellus ");
        printf("et aliquet nisi, et eleifend jus");
        printf("to. Etiam vulputate urna sed lac");
        printf("us fringilla hendrerit vel sed l");
        printf("eo. Vestibulum ultrices ac velit");
        printf(" non imperdiet. Nunc eu dolor vo");
        printf("lutpat, fermentum ex non, tempor");
        printf(" tortor. Vivamus nec lectus vita");
        printf("e eros mattis tristique. Quisque");
        printf(" condimentum, leo eu cursus luct");
        printf("us, elit risus lobortis dui, qui");
        printf("s tempus metus metus eu ante. Ut");
        printf(" faucibus rhoncus augue. Praesen");
        printf("t nec mattis tellus, eu volutpat");
        printf(" libero.  Nulla pulvinar at sem ");
        printf("sed placerat. Cras commodo mi eu");
        printf(" mauris convallis vehicula. Etia");
        printf("m mattis nisl orci, accumsan sol");
        printf("licitudin est pulvinar id. Vivam");
        printf("us sollicitudin justo sed lorem ");
        printf("fermentum, ac porta erat molesti");
        printf("e. Morbi dictum posuere risus, a");
        printf("t venenatis magna malesuada ut. ");
        printf("Vestibulum pretium lacus tempor ");
        printf("urna pellentesque, non bibendum ");
        printf("neque varius. Proin tristique ma");
        printf("uris in felis convallis, ut blan");
        printf("dit massa convallis. Mauris ut v");
        printf("elit ultrices, rhoncus ligula vi");
        printf("tae, aliquet sem.  Fusce volutpa");
        printf("t ante quis arcu viverra venenat");
        printf("is. Phasellus vel neque erat. Cr");
        printf("as viverra augue sapien, non con");
        printf("dimentum augue maximus non. Morb");
        printf("i mattis fringilla eleifend. Cur");
        printf("abitur ut augue et lacus loborti");
        printf("s malesuada vitae et sem. Nunc v");
        printf("olutpat lacinia eros ac placerat");
        printf(". Vestibulum ornare venenatis di");
        printf("ctum. Mauris ac nibh sed est iac");
        printf("ulis laoreet ac nec mauris.  Int");
        printf("eger cursus rutrum ante, in plac");
        printf("erat diam condimentum et. Praese");
        printf("nt a neque sit amet mi condiment");
        printf("um malesuada et suscipit nunc. V");
        printf("ivamus eu lacus orci. Donec metu");
        printf("s urna, iaculis id congue et, or");
        printf("nare in elit. Fusce tempus sem v");
        printf("itae dolor accumsan feugiat. Don");
        printf("ec vel mollis ex, et sagittis ju");
        printf("sto. Suspendisse laoreet molesti");
        printf("e odio in vehicula. Nunc varius ");
        printf("nulla eu turpis gravida consecte");
        printf("tur. Integer luctus porta accums");
        printf("an.  In a mollis nunc. Vestibulu");
        printf("m scelerisque metus sed mauris u");
        printf("llamcorper, at lacinia risus tem");
        printf("pus. Praesent consequat orci ac ");
        printf("fringilla pretium. Aenean eleife");
        printf("nd augue nec ex tempor, vel temp");
        printf("or arcu ullamcorper. Aenean nec ");
        printf("consectetur magna. Sed condiment");
        printf("um luctus velit eget blandit. Al");
        printf("iquam ut risus eros. Integer fau");
        printf("cibus est turpis. In faucibus es");
        printf("t nisi, non rhoncus velit fringi");
        printf("lla quis. In hac habitasse plate");
        printf("a dictumst.  Aenean eleifend ac ");
        printf("nibh ut sodales. Duis blandit co");
        printf("nsequat arcu porttitor tincidunt");
        printf(". Ut vitae est vitae arcu dapibu");
        printf("s mattis. Nam cursus eget justo ");
        printf("in faucibus. Vivamus dictum ex s");
        printf("ed nisi pretium auctor. Nulla fa");
        printf("cilisi. Ut efficitur pellentesqu");
        printf("e placerat.  Nulla quis laoreet ");
        printf("lectus. Sed vitae blandit magna.");
        printf(" Aliquam accumsan ipsum et scele");
        printf("risque tristique. Duis lacinia a");
        printf(" urna non porta. Pellentesque ha");
        printf("bitant morbi tristique senectus ");
        printf("et netus et malesuada fames ac t");
        printf("urpis egestas. Aenean finibus nu");
        printf("lla ac convallis ultrices. Proin");
        printf(" viverra mollis lorem sit amet v");
        printf("arius. Nunc ante sem, dignissim ");
        printf("eu cursus vel, volutpat eget lac");
        printf("us. Quisque enim ex, venenatis e");
        printf("t semper et, suscipit sed nulla.");
        printf(" Aenean aliquet molestie velit s");
        printf("it amet dignissim. Mauris lobort");
        printf("is dui nisl, vel eleifend est di");
        printf("ctum vel. Cras lobortis pretium ");
        printf("ante sit amet tempus. Donec ultr");
        printf("icies tempus interdum. Suspendis");
        printf("se eget ultricies ipsum, sed fac");
        printf("ilisis est. Aliquam vitae gravid");
        printf("a odio. Ut congue egestas sem, s");
        printf("ed luctus lacus viverra vitae.  ");
        printf("Integer sagittis feugiat leo, qu");
        printf("is molestie diam dictum vitae. V");
        printf("estibulum ante ipsum primis in f");
        printf("aucibus orci luctus et ultrices ");
        printf("posuere cubilia curae; Aenean qu");
        printf("is justo et est viverra malesuad");
        printf("a non quis lectus. In hac habita");
        printf("sse platea dictumst. Sed vitae u");
        printf("rna vel odio volutpat semper con");
        printf("sectetur a mi. Integer sollicitu");
        printf("din, metus at volutpat ultricies");
        printf(", risus enim pulvinar magna, ac ");
        printf("faucibus nisl lectus vitae odio.");
        printf(" Sed sit amet malesuada eros. Nu");
        printf("nc vestibulum elit eu lectus tri");
        printf("stique malesuada. Mauris pellent");
        printf("esque elit eget vehicula fringil");
        printf("la. Etiam tincidunt libero quis ");
        printf("orci pharetra, quis condimentum ");
        printf("dolor fermentum. Donec justo tur");
        printf("pis, sagittis varius leo vel, ma");
        printf("ttis rhoncus nunc. Suspendisse n");
        printf("on nunc bibendum, tincidunt nequ");
        printf("e et, imperdiet erat. Maecenas a");
        printf("nte velit, iaculis et cursus vel");
        printf(", accumsan eget nulla. Integer t");
        printf("incidunt, metus eu luctus ultric");
        printf("ies, leo mauris posuere ipsum, e");
        printf("get commodo lacus libero ut tort");
        printf("or. Pellentesque molestie enim p");
        printf("osuere tellus luctus dapibus.  C");
        printf("urabitur pharetra nibh et purus ");
        printf("maximus, in dapibus lectus conse");
        printf("quat. Curabitur nec faucibus eli");
        printf("t, eu volutpat dolor. Interdum e");
        printf("t malesuada fames ac ante ipsum ");
        printf("primis in faucibus. Vestibulum l");
        printf("obortis tempus mauris eget fring");
        printf("illa. Aliquam non orci eu diam i");
        printf("mperdiet feugiat. Quisque congue");
        printf(" urna sed est laoreet, et blandi");
        printf("t ex pharetra. Nam commodo hendr");
        printf("erit mattis. Suspendisse a rhonc");
        printf("us sapien. Nulla nibh mauris, ia");
        printf("culis vitae tellus nec, posuere ");
        printf("dapibus nunc. Lorem ipsum dolor ");
        printf("sit amet, consectetur adipiscing");
        printf(" elit. Integer faucibus sollicit");
        printf("udin lacus, vitae luctus nunc mo");
        printf("llis vel.  Nam quis ipsum quis v");
        printf("elit porttitor lacinia. Phasellu");
        printf("s at ligula eu quam mollis inter");
        printf("dum. Integer porta neque eu tort");
        printf("or viverra, sit amet interdum tu");
        printf("rpis dignissim. Aenean posuere t");
        printf("incidunt facilisis. Duis malesua");
        printf("da malesuada metus, eu euismod e");
        printf("rat iaculis et. Curabitur nec mo");
        printf("lestie magna, eu cursus sem. Dui");
        printf("s tincidunt pellentesque ligula ");
        printf("in mollis. Quisque et venenatis ");
        printf("magna. In laoreet, dolor eget al");
        printf("iquet condimentum, elit metus lu");
        printf("ctus nibh, at pellentesque torto");
        printf("r sem sit amet mauris. Pellentes");
        printf("que placerat, augue nec feugiat ");
        printf("rhoncus, sapien erat feugiat met");
        printf("us, ultricies dignissim arcu mau");
        printf("ris. ");
    #endif

    #if BENCHMARK_ULOG_SIZE
        ULOG_DBG("  Lorem ipsum dolor sit amet, co");
        ULOG_DBG("nsectetur adipiscing elit. In si");
        ULOG_DBG("t amet sem eget ligula consequat");
        ULOG_DBG(" hendrerit. Etiam pulvinar tempo");
        ULOG_DBG("r lorem, lacinia dictum massa ma");
        ULOG_DBG("ttis ut. Mauris vulputate vulput");
        ULOG_DBG("ate lectus sit amet congue. Maur");
        ULOG_DBG("is feugiat ipsum in purus maximu");
        ULOG_DBG("s, quis sagittis est fermentum. ");
        ULOG_DBG("Nunc a lorem luctus, dapibus nis");
        ULOG_DBG("l sit amet, sodales lacus. Pelle");
        ULOG_DBG("ntesque fringilla lectus sed dia");
        ULOG_DBG("m convallis, sit amet dapibus lo");
        ULOG_DBG("rem rhoncus. Quisque laoreet lib");
        ULOG_DBG("ero vel efficitur varius.  In gr");
        ULOG_DBG("avida consectetur massa nec faci");
        ULOG_DBG("lisis. Integer dolor lorem, cond");
        ULOG_DBG("imentum ac arcu ultricies, dictu");
        ULOG_DBG("m faucibus dui. Sed tellus justo");
        ULOG_DBG(", gravida ac mattis at, semper u");
        ULOG_DBG("t ex. Quisque aliquam ipsum vita");
        ULOG_DBG("e elementum accumsan. Donec at a");
        ULOG_DBG("uctor dui. Sed maximus vulputate");
        ULOG_DBG(" lectus, vitae dignissim magna c");
        ULOG_DBG("ursus nec. Aenean luctus, neque ");
        ULOG_DBG("et scelerisque placerat, odio ni");
        ULOG_DBG("si sagittis augue, quis tristiqu");
        ULOG_DBG("e felis lacus eget arcu.  Quisqu");
        ULOG_DBG("e faucibus nibh risus, nec conse");
        ULOG_DBG("ctetur lacus condimentum nec. Se");
        ULOG_DBG("d vitae orci lacus. Nullam trist");
        ULOG_DBG("ique tempor magna, a porta orci ");
        ULOG_DBG("venenatis vel. Vestibulum ultric");
        ULOG_DBG("es sem vel nisl pharetra vulputa");
        ULOG_DBG("te. Ut interdum dui sed tortor m");
        ULOG_DBG("olestie molestie. Morbi pellente");
        ULOG_DBG("sque ex vel tortor placerat aliq");
        ULOG_DBG("uam. Vivamus velit eros, mollis ");
        ULOG_DBG("posuere mauris in, volutpat aliq");
        ULOG_DBG("uet augue. Nunc at pellentesque ");
        ULOG_DBG("odio. Morbi tristique turpis a e");
        ULOG_DBG("st tincidunt, sit amet tincidunt");
        ULOG_DBG(" nisl consequat. Duis vel erat l");
        ULOG_DBG("uctus, aliquet nulla eu, tincidu");
        ULOG_DBG("nt odio. Mauris hendrerit massa ");
        ULOG_DBG("at massa congue tristique. Pelle");
        ULOG_DBG("ntesque bibendum hendrerit moles");
        ULOG_DBG("tie. Nulla libero justo, vulputa");
        ULOG_DBG("te sed odio eget, mollis tempus ");
        ULOG_DBG("nisi. Mauris finibus vel neque q");
        ULOG_DBG("uis ultrices. Quisque rutrum nib");
        ULOG_DBG("h et turpis rutrum, et imperdiet");
        ULOG_DBG(" turpis pellentesque.  Nam ante ");
        ULOG_DBG("turpis, pharetra quis velit vel,");
        ULOG_DBG(" feugiat lacinia nunc. Phasellus");
        ULOG_DBG(" commodo sagittis nunc, ut conva");
        ULOG_DBG("llis mauris pretium vel. Aenean ");
        ULOG_DBG("felis justo, elementum id velit ");
        ULOG_DBG("quis, lobortis pretium dolor. Se");
        ULOG_DBG("d consectetur tempus ipsum at ul");
        ULOG_DBG("lamcorper. In a felis metus. Eti");
        ULOG_DBG("am scelerisque feugiat lacus vit");
        ULOG_DBG("ae molestie. Pellentesque vitae ");
        ULOG_DBG("arcu eu erat aliquet hendrerit a");
        ULOG_DBG("c vitae dui. In sed maximus nunc");
        ULOG_DBG(", lacinia dignissim risus. Nulla");
        ULOG_DBG(" eget urna mollis, euismod massa");
        ULOG_DBG(" quis, viverra mauris.  Quisque ");
        ULOG_DBG("dignissim consequat nunc nec fac");
        ULOG_DBG("ilisis. Sed molestie sem quis se");
        ULOG_DBG("m scelerisque, a fermentum torto");
        ULOG_DBG("r lacinia. Etiam tincidunt euism");
        ULOG_DBG("od nisl vitae auctor. Sed nec ar");
        ULOG_DBG("cu congue tellus facilisis lobor");
        ULOG_DBG("tis sit amet quis arcu. Nunc sit");
        ULOG_DBG(" amet orci vulputate, suscipit f");
        ULOG_DBG("elis non, euismod lacus. Vivamus");
        ULOG_DBG(" malesuada, sapien in mollis dic");
        ULOG_DBG("tum, mauris neque consequat risu");
        ULOG_DBG("s, eget sagittis ante quam ut du");
        ULOG_DBG("i. Suspendisse convallis tristiq");
        ULOG_DBG("ue nulla. Maecenas viverra metus");
        ULOG_DBG(" vel fringilla imperdiet. Duis i");
        ULOG_DBG("n magna at sapien viverra tempus");
        ULOG_DBG(" eu eu sapien. Integer id dignis");
        ULOG_DBG("sim nisl. Mauris turpis dolor, d");
        ULOG_DBG("ignissim in mattis malesuada, eg");
        ULOG_DBG("estas quis ligula. Praesent at e");
        ULOG_DBG("lit ultrices, consequat lorem at");
        ULOG_DBG(", fermentum justo. Morbi aliquam");
        ULOG_DBG(" ultricies molestie. Nunc finibu");
        ULOG_DBG("s augue sit amet est ullamcorper");
        ULOG_DBG(", ultricies rhoncus sapien ullam");
        ULOG_DBG("corper. Vestibulum ante ipsum pr");
        ULOG_DBG("imis in faucibus orci luctus et ");
        ULOG_DBG("ultrices posuere cubilia curae; ");
        ULOG_DBG(" Curabitur commodo turpis in pla");
        ULOG_DBG("cerat cursus. Fusce quis ligula ");
        ULOG_DBG("dignissim eros lobortis iaculis ");
        ULOG_DBG("eu nec dolor. Aenean eleifend fe");
        ULOG_DBG("lis massa, quis vehicula odio so");
        ULOG_DBG("llicitudin ut. Quisque quis blan");
        ULOG_DBG("dit lacus. Sed sit amet massa fe");
        ULOG_DBG("ugiat, blandit dui ac, tempor od");
        ULOG_DBG("io. Duis vel turpis a urna digni");
        ULOG_DBG("ssim faucibus. Praesent tincidun");
        ULOG_DBG("t turpis eu purus pretium faucib");
        ULOG_DBG("us. Pellentesque gravida, diam i");
        ULOG_DBG("d venenatis ornare, nunc nibh sa");
        ULOG_DBG("gittis nulla, sed porttitor ante");
        ULOG_DBG(" lacus in mauris. Aenean accumsa");
        ULOG_DBG("n elementum nisi in tristique. A");
        ULOG_DBG("enean turpis magna, volutpat ege");
        ULOG_DBG("t libero non, tincidunt porta er");
        ULOG_DBG("at.  Sed finibus tristique laore");
        ULOG_DBG("et. Nam id dolor nisi. Orci vari");
        ULOG_DBG("us natoque penatibus et magnis d");
        ULOG_DBG("is parturient montes, nascetur r");
        ULOG_DBG("idiculus mus. Cras ornare elemen");
        ULOG_DBG("tum blandit. Suspendisse tempus ");
        ULOG_DBG("odio nec bibendum ornare. Aliqua");
        ULOG_DBG("m malesuada ex at tortor ultrici");
        ULOG_DBG("es vulputate. Sed vehicula mauri");
        ULOG_DBG("s ipsum, id maximus urna sceleri");
        ULOG_DBG("sque ut. Maecenas facilisis veli");
        ULOG_DBG("t sit amet tellus iaculis, ut po");
        ULOG_DBG("rttitor est blandit. Suspendisse");
        ULOG_DBG(" ante tortor, tempor in dolor ut");
        ULOG_DBG(", cursus lacinia ligula. Proin h");
        ULOG_DBG("endrerit, nisi a semper fringill");
        ULOG_DBG("a, libero sapien dapibus ipsum, ");
        ULOG_DBG("et faucibus tortor quam eget eni");
        ULOG_DBG("m.  Ut tincidunt lectus vel maur");
        ULOG_DBG("is iaculis eleifend. Proin id ex");
        ULOG_DBG(" id ante dignissim auctor in nec");
        ULOG_DBG(" sem. Nunc consectetur cursus du");
        ULOG_DBG("i, vel accumsan metus dignissim ");
        ULOG_DBG("sit amet. Sed quis urna quis leo");
        ULOG_DBG(" scelerisque dapibus rutrum at l");
        ULOG_DBG("igula. In fermentum leo quis era");
        ULOG_DBG("t varius interdum. Duis vehicula");
        ULOG_DBG(" est imperdiet molestie bibendum");
        ULOG_DBG(". Morbi sagittis pretium tortor,");
        ULOG_DBG(" at commodo nulla tincidunt eget");
        ULOG_DBG(". Nunc mi ante, suscipit sit ame");
        ULOG_DBG("t lectus ac, vehicula volutpat l");
        ULOG_DBG("igula.  Cras ut nisi blandit, pu");
        ULOG_DBG("lvinar dui ut, egestas mauris. P");
        ULOG_DBG("hasellus quis augue vitae odio f");
        ULOG_DBG("aucibus lacinia eget sit amet du");
        ULOG_DBG("i. Nunc tristique, tortor non so");
        ULOG_DBG("dales ornare, mi leo dignissim e");
        ULOG_DBG("ros, ut ultrices massa ante sit ");
        ULOG_DBG("amet augue. Fusce molestie dui i");
        ULOG_DBG("d consectetur tempus. Phasellus ");
        ULOG_DBG("et aliquet nisi, et eleifend jus");
        ULOG_DBG("to. Etiam vulputate urna sed lac");
        ULOG_DBG("us fringilla hendrerit vel sed l");
        ULOG_DBG("eo. Vestibulum ultrices ac velit");
        ULOG_DBG(" non imperdiet. Nunc eu dolor vo");
        ULOG_DBG("lutpat, fermentum ex non, tempor");
        ULOG_DBG(" tortor. Vivamus nec lectus vita");
        ULOG_DBG("e eros mattis tristique. Quisque");
        ULOG_DBG(" condimentum, leo eu cursus luct");
        ULOG_DBG("us, elit risus lobortis dui, qui");
        ULOG_DBG("s tempus metus metus eu ante. Ut");
        ULOG_DBG(" faucibus rhoncus augue. Praesen");
        ULOG_DBG("t nec mattis tellus, eu volutpat");
        ULOG_DBG(" libero.  Nulla pulvinar at sem ");
        ULOG_DBG("sed placerat. Cras commodo mi eu");
        ULOG_DBG(" mauris convallis vehicula. Etia");
        ULOG_DBG("m mattis nisl orci, accumsan sol");
        ULOG_DBG("licitudin est pulvinar id. Vivam");
        ULOG_DBG("us sollicitudin justo sed lorem ");
        ULOG_DBG("fermentum, ac porta erat molesti");
        ULOG_DBG("e. Morbi dictum posuere risus, a");
        ULOG_DBG("t venenatis magna malesuada ut. ");
        ULOG_DBG("Vestibulum pretium lacus tempor ");
        ULOG_DBG("urna pellentesque, non bibendum ");
        ULOG_DBG("neque varius. Proin tristique ma");
        ULOG_DBG("uris in felis convallis, ut blan");
        ULOG_DBG("dit massa convallis. Mauris ut v");
        ULOG_DBG("elit ultrices, rhoncus ligula vi");
        ULOG_DBG("tae, aliquet sem.  Fusce volutpa");
        ULOG_DBG("t ante quis arcu viverra venenat");
        ULOG_DBG("is. Phasellus vel neque erat. Cr");
        ULOG_DBG("as viverra augue sapien, non con");
        ULOG_DBG("dimentum augue maximus non. Morb");
        ULOG_DBG("i mattis fringilla eleifend. Cur");
        ULOG_DBG("abitur ut augue et lacus loborti");
        ULOG_DBG("s malesuada vitae et sem. Nunc v");
        ULOG_DBG("olutpat lacinia eros ac placerat");
        ULOG_DBG(". Vestibulum ornare venenatis di");
        ULOG_DBG("ctum. Mauris ac nibh sed est iac");
        ULOG_DBG("ulis laoreet ac nec mauris.  Int");
        ULOG_DBG("eger cursus rutrum ante, in plac");
        ULOG_DBG("erat diam condimentum et. Praese");
        ULOG_DBG("nt a neque sit amet mi condiment");
        ULOG_DBG("um malesuada et suscipit nunc. V");
        ULOG_DBG("ivamus eu lacus orci. Donec metu");
        ULOG_DBG("s urna, iaculis id congue et, or");
        ULOG_DBG("nare in elit. Fusce tempus sem v");
        ULOG_DBG("itae dolor accumsan feugiat. Don");
        ULOG_DBG("ec vel mollis ex, et sagittis ju");
        ULOG_DBG("sto. Suspendisse laoreet molesti");
        ULOG_DBG("e odio in vehicula. Nunc varius ");
        ULOG_DBG("nulla eu turpis gravida consecte");
        ULOG_DBG("tur. Integer luctus porta accums");
        ULOG_DBG("an.  In a mollis nunc. Vestibulu");
        ULOG_DBG("m scelerisque metus sed mauris u");
        ULOG_DBG("llamcorper, at lacinia risus tem");
        ULOG_DBG("pus. Praesent consequat orci ac ");
        ULOG_DBG("fringilla pretium. Aenean eleife");
        ULOG_DBG("nd augue nec ex tempor, vel temp");
        ULOG_DBG("or arcu ullamcorper. Aenean nec ");
        ULOG_DBG("consectetur magna. Sed condiment");
        ULOG_DBG("um luctus velit eget blandit. Al");
        ULOG_DBG("iquam ut risus eros. Integer fau");
        ULOG_DBG("cibus est turpis. In faucibus es");
        ULOG_DBG("t nisi, non rhoncus velit fringi");
        ULOG_DBG("lla quis. In hac habitasse plate");
        ULOG_DBG("a dictumst.  Aenean eleifend ac ");
        ULOG_DBG("nibh ut sodales. Duis blandit co");
        ULOG_DBG("nsequat arcu porttitor tincidunt");
        ULOG_DBG(". Ut vitae est vitae arcu dapibu");
        ULOG_DBG("s mattis. Nam cursus eget justo ");
        ULOG_DBG("in faucibus. Vivamus dictum ex s");
        ULOG_DBG("ed nisi pretium auctor. Nulla fa");
        ULOG_DBG("cilisi. Ut efficitur pellentesqu");
        ULOG_DBG("e placerat.  Nulla quis laoreet ");
        ULOG_DBG("lectus. Sed vitae blandit magna.");
        ULOG_DBG(" Aliquam accumsan ipsum et scele");
        ULOG_DBG("risque tristique. Duis lacinia a");
        ULOG_DBG(" urna non porta. Pellentesque ha");
        ULOG_DBG("bitant morbi tristique senectus ");
        ULOG_DBG("et netus et malesuada fames ac t");
        ULOG_DBG("urpis egestas. Aenean finibus nu");
        ULOG_DBG("lla ac convallis ultrices. Proin");
        ULOG_DBG(" viverra mollis lorem sit amet v");
        ULOG_DBG("arius. Nunc ante sem, dignissim ");
        ULOG_DBG("eu cursus vel, volutpat eget lac");
        ULOG_DBG("us. Quisque enim ex, venenatis e");
        ULOG_DBG("t semper et, suscipit sed nulla.");
        ULOG_DBG(" Aenean aliquet molestie velit s");
        ULOG_DBG("it amet dignissim. Mauris lobort");
        ULOG_DBG("is dui nisl, vel eleifend est di");
        ULOG_DBG("ctum vel. Cras lobortis pretium ");
        ULOG_DBG("ante sit amet tempus. Donec ultr");
        ULOG_DBG("icies tempus interdum. Suspendis");
        ULOG_DBG("se eget ultricies ipsum, sed fac");
        ULOG_DBG("ilisis est. Aliquam vitae gravid");
        ULOG_DBG("a odio. Ut congue egestas sem, s");
        ULOG_DBG("ed luctus lacus viverra vitae.  ");
        ULOG_DBG("Integer sagittis feugiat leo, qu");
        ULOG_DBG("is molestie diam dictum vitae. V");
        ULOG_DBG("estibulum ante ipsum primis in f");
        ULOG_DBG("aucibus orci luctus et ultrices ");
        ULOG_DBG("posuere cubilia curae; Aenean qu");
        ULOG_DBG("is justo et est viverra malesuad");
        ULOG_DBG("a non quis lectus. In hac habita");
        ULOG_DBG("sse platea dictumst. Sed vitae u");
        ULOG_DBG("rna vel odio volutpat semper con");
        ULOG_DBG("sectetur a mi. Integer sollicitu");
        ULOG_DBG("din, metus at volutpat ultricies");
        ULOG_DBG(", risus enim pulvinar magna, ac ");
        ULOG_DBG("faucibus nisl lectus vitae odio.");
        ULOG_DBG(" Sed sit amet malesuada eros. Nu");
        ULOG_DBG("nc vestibulum elit eu lectus tri");
        ULOG_DBG("stique malesuada. Mauris pellent");
        ULOG_DBG("esque elit eget vehicula fringil");
        ULOG_DBG("la. Etiam tincidunt libero quis ");
        ULOG_DBG("orci pharetra, quis condimentum ");
        ULOG_DBG("dolor fermentum. Donec justo tur");
        ULOG_DBG("pis, sagittis varius leo vel, ma");
        ULOG_DBG("ttis rhoncus nunc. Suspendisse n");
        ULOG_DBG("on nunc bibendum, tincidunt nequ");
        ULOG_DBG("e et, imperdiet erat. Maecenas a");
        ULOG_DBG("nte velit, iaculis et cursus vel");
        ULOG_DBG(", accumsan eget nulla. Integer t");
        ULOG_DBG("incidunt, metus eu luctus ultric");
        ULOG_DBG("ies, leo mauris posuere ipsum, e");
        ULOG_DBG("get commodo lacus libero ut tort");
        ULOG_DBG("or. Pellentesque molestie enim p");
        ULOG_DBG("osuere tellus luctus dapibus.  C");
        ULOG_DBG("urabitur pharetra nibh et purus ");
        ULOG_DBG("maximus, in dapibus lectus conse");
        ULOG_DBG("quat. Curabitur nec faucibus eli");
        ULOG_DBG("t, eu volutpat dolor. Interdum e");
        ULOG_DBG("t malesuada fames ac ante ipsum ");
        ULOG_DBG("primis in faucibus. Vestibulum l");
        ULOG_DBG("obortis tempus mauris eget fring");
        ULOG_DBG("illa. Aliquam non orci eu diam i");
        ULOG_DBG("mperdiet feugiat. Quisque congue");
        ULOG_DBG(" urna sed est laoreet, et blandi");
        ULOG_DBG("t ex pharetra. Nam commodo hendr");
        ULOG_DBG("erit mattis. Suspendisse a rhonc");
        ULOG_DBG("us sapien. Nulla nibh mauris, ia");
        ULOG_DBG("culis vitae tellus nec, posuere ");
        ULOG_DBG("dapibus nunc. Lorem ipsum dolor ");
        ULOG_DBG("sit amet, consectetur adipiscing");
        ULOG_DBG(" elit. Integer faucibus sollicit");
        ULOG_DBG("udin lacus, vitae luctus nunc mo");
        ULOG_DBG("llis vel.  Nam quis ipsum quis v");
        ULOG_DBG("elit porttitor lacinia. Phasellu");
        ULOG_DBG("s at ligula eu quam mollis inter");
        ULOG_DBG("dum. Integer porta neque eu tort");
        ULOG_DBG("or viverra, sit amet interdum tu");
        ULOG_DBG("rpis dignissim. Aenean posuere t");
        ULOG_DBG("incidunt facilisis. Duis malesua");
        ULOG_DBG("da malesuada metus, eu euismod e");
        ULOG_DBG("rat iaculis et. Curabitur nec mo");
        ULOG_DBG("lestie magna, eu cursus sem. Dui");
        ULOG_DBG("s tincidunt pellentesque ligula ");
        ULOG_DBG("in mollis. Quisque et venenatis ");
        ULOG_DBG("magna. In laoreet, dolor eget al");
        ULOG_DBG("iquet condimentum, elit metus lu");
        ULOG_DBG("ctus nibh, at pellentesque torto");
        ULOG_DBG("r sem sit amet mauris. Pellentes");
        ULOG_DBG("que placerat, augue nec feugiat ");
        ULOG_DBG("rhoncus, sapien erat feugiat met");
        ULOG_DBG("us, ultricies dignissim arcu mau");
        ULOG_DBG("ris. ");
    #endif
}
